baseURL = 'https://sheel2007.github.io/blog/'
publishDir = 'docs'
languageCode = 'en-us'
title = 'Blog Page'

paginate = 4

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"